FROM python:3.8

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONIOENCODING=utf-8
ENV APP_SETTINGS=/project/etc/ccmmmaapi.conf

RUN apt update
RUN apt-get install -y --no-install-recommends libatlas-base-dev gfortran tilde logrotate vim

COPY ./requirements.txt /project/requirements.txt
RUN pip3 install -r /project/requirements.txt

#RUN echo 'root:7fZ!p9Ls&XvG3bQd' | chpasswd

RUN groupadd -g 3001 ccmmma
RUN useradd -m -u 3001 -g 3001 -s /bin/bash ccmmma
USER ccmmma

COPY --chown=ccmmma:ccmmma . /project
WORKDIR /project

#CMD ["uwsgi", "--ini", "ccmmmaapi-test.ini", "--uid", "ccmmma"]
# ENTRYPOINT ["tail", "-f", "/dev/null"]
ENTRYPOINT ["uwsgi", "--ini", "ccmmmaapi-test.ini", "--uid", "ccmmma"]
# uwsgi --ini ccmmmaapi.ini --uid ccmmma
