#This is is an API configuration file example

HOME_URL = "https://api.meteo.uniparthenope.it"
CHART_PAGE = "/chart/chart"
TABLE_PAGE  = "/table/table"
FORECAST_PAGE = "/forecast/forecast"
BASE_PATH = "/data1/ccmmma/prometeo/data/opendap/"
BASE_STORAGE_PATH = "/storage/ccmmma/prometeo/data/opendap/"
PRODS_PATH = "/project/var/prods/"
VARS_CONTROL_PATH = "/project/vars-control-file/"
BASE_URL = "https://api.meteo.uniparthenope.it"
DODS_URL = "https://api.meteo.uniparthenope.it/opendap/%s/%s/%s/%s"
WMS_URL = "https://api.meteo.uniparthenope.it/ncWMS2/wms"
BASE_PRODUCTS = "/project/images"
#TODO: add 'no-image.png'
NOIMAGE_URL = "https://meteo.uniparthenope.it/images/noimage.png"
NOIMAGE_PATH = "/project/images/noimage.png"
NOIMAGE_URL = "https://api.meteo.uniparthenope.it/images/noimage.png"
NOIMAGE_PATH = "/data1/ccmmma/prometeo/www/images/noimage.png"
PUB_URL = "https://api.meteo.uniparthenope.it/images"
DATABASE = "ccmmma-database"
NUM_THREADS = 1
LEGAL = "/project/etc/legal.json"
MAPS = "/project/etc/maps.json"
LANG = "en-US"
PAGES = "/projects/etc/pages.json"
HISTORY = "archive"
ARCHIVE = "archive"
ENV = "production"
CACHE_TIMEOUT = 3600

# memcached
#list of memcached servers available comma separated
#servers=192.168.241.35
#servers=["127.0.0.1"]
